# Generated by Django 3.0.8 on 2020-11-01 20:20

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Must include international prefix - e.g. +1 555 555 55555', max_length=128, region=None)),
                ('description', models.TextField(help_text='A description of your problem')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
